// swift-tools-version: 6.2
// The macOS side of the project: `affect-replay` compiles the app's real emotion
// engine (Sources/AffectEngine, the same files the visionOS app builds) into a
// command-line tool that runs it over video files. The visionOS app itself is
// generated by XcodeGen from project.yml.
import PackageDescription

let package = Package(
    name: "AffectLens",
    platforms: [.macOS("26.0")],
    targets: [
        .executableTarget(
            name: "affect-replay",
            path: "Sources",
            // The engine, the harness, and the one UI file whose pure helpers
            // (uncertainty palette, dotplot quantiles, aura ramp) the self-tests cover.
            sources: ["AffectEngine", "Harness", "AffectUI/UncertaintyWidgets.swift"],
            swiftSettings: [
                // Same isolation model as the app target (Xcode 26 template default).
                .defaultIsolation(MainActor.self),
                .swiftLanguageMode(.v5),
            ]
        ),
    ]
)
